[package]
name = "pj"
version = "0.1.0"
authors = ["jon"]
edition = "2021"

[dependencies]
serde_json = "1.0"

# https://github.com/johnthagen/min-sized-rust#strip-symbols-from-binary
[profile.release]
strip = true
lto = true
opt-level = "z"
